### ISSUE TITLE
[FIX] 회원 API 미작동 오류 수정

### ISSUE THREAD

**Issue by gmkim20713** [local-mood/ceos-vote-server#33]
# Summary
회원가입, 로그인, 로그아웃, 토큰 관련 API 전반 수정 (문제 해결 + 리팩토링)

## Problem
- Swagger로 테스트 시 동작하지 않는 API 존재

## To-do
- [x] Resxponse Body 사용 방식으로 변경
- [x] Authorization Header 사용 방식으로 변경
- [x] 쿠키 path 지정
- [x] RequestDto 리팩 + SET_COOKIE 헤더 추가
