### ISSUE TITLE
[FIX] 멤버(파트장) 조회, 투표 API 파트 별 분리

### ISSUE THREAD

**Issue by gmkim20713** [local-mood/ceos-vote-server#61]
# Summary
멤버(파트장) 조회, 투표 API 파트 별 분리

## Problem
- 파트 별 조회, 각 파트 당 1회 투표가 불가능한 상황이었음

## To-do
- [x] Member 엔티티 수정 (컬럼 변경)
- [x] 멤버 조회 API 수정
- [x] 멤버 투표 API 수정
